package main

var stopwords = []string{
	"shouldn", "by", "until", "having", "ourselves",
	"few", "doesn't", "am", "d", "their",
	"should've", "a", "up", "did", "down", "how", "didn't",
	"but", "against", "her", "he", "that", "my", "that'll",
	"its", "than", "does", "no", "shouldn't",
	"most", "after", "further", "yourselves",
	"if", "there", "haven", "wasn\"t", "t", "or", "at", "weren", "just", "hasn\"t", "couldn\"t", "those", "hadn\"t", "because", "i", "they", "our", "through", "above", "being", "hasn", "o", "isn", "each",
	"on", "all", "themselves", "which", "any", "again", "needn\"t", "won\"t", "do", "you\"ve",
	"theirs", "now", "it", "so", "in", "ve", "over", "didn", "own", "aren", "myself",
	"you\"ll", "s", "from", "have", "ours", "other", "wouldn", "very", "to", "don", "doesn", "an", "isn\"t",
	"not", "doing", "under", "then", "between", "yours", "she\"s",
	"mightn\"t", "don\"t", "for", "out", "couldn", "was", "why", "both", "should", "about", "his", "once",
	"itself", "she", "wasn", "can", "this", "who", "we", "your", "m", "needn", "before",
	"same", "be", "and", "into", "shan\"t", "is", "shan", "hers", "aren\"t", "here", "of", "the", "where", "mustn", "some", "are", "nor",
	"too", "with", "below", "been", "these", "ain", "what", "as", "y", "yourself", "wouldn\"t", "while", "him", "herself", "had", "ma",
	"mustn\"t", "you\"re", "such", "mightn", "himself",
	"whom", "it\"s", "more", "only", "hadn", "off", "haven\"t", "ll", "during", "weren\"t", "you", "me",
	"were", "won", "will", "them", "has", "re", "you\"d", "when", "shouldn", "by", "until", "having", "ourselves", "few", "doesn\"t", "am", "d", "their",
	"should\"ve", "a", "up", "did", "down", "how", "didn\"t", "but", "against", "her", "he", "that", "my", "that\"ll", "its",
	"than", "does", "no", "shouldn\"t", "most", "after", "further", "yourselves",
	"if", "there", "haven", "wasn\"t", "t", "or", "at", "weren", "just", "hasn\"t", "couldn\"t", "those", "hadn\"t", "because", "i",
	"they", "our", "through", "above", "being", "hasn", "o", "isn", "each", "on", "all", "themselves", "which", "any",
	"again", "needn\"t", "won\"t", "do", "you\"ve", "theirs", "now", "it", "so", "in", "ve", "over", "didn", "own",
	"aren", "myself", "you\"ll", "s", "from", "have", "ours", "other", "wouldn", "very", "to", "don", "doesn", "an",
	"isn\"t", "not", "doing", "under", "then", "between", "yours", "she\"s", "mightn\"t", "don\"t", "for", "out", "couldn", "was", "why", "both",
	"should", "about", "his", "once", "itself", "she", "wasn", "can", "this", "who", "we", "your", "m", "needn", "before", "same", "be", "and", "into",
	"shan\"t", "is", "shan", "hers", "aren\"t", "here", "of", "the", "where", "mustn", "some", "are", "nor", "too", "with", "below", "been",
	"these", "ain", "what", "as", "y", "yourself", "wouldn\"t", "while", "him", "herself", "had", "ma", "mustn\"t",
	"you\"re", "such", "mightn", "himself", "whom", "it\"s", "more", "only", "hadn", "off", "haven\"t", "ll", "during", "weren\"t", "you", "me", "were", "won", "will", "them", "has", "re",
	"you\"d", "when"}
